# Generated by Django 2.1.7 on 2020-04-23 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='时间')),
                ('content_type', models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='对象')),
                ('object_id', models.IntegerField(verbose_name='对象ID')),
                ('object_repr', models.CharField(max_length=200, verbose_name='对象')),
                ('action_flag', models.PositiveSmallIntegerField(choices=[(1, '添加'), (2, '修改'), (3, '删除')], verbose_name='操作标志')),
                ('message', models.TextField(blank=True, verbose_name='变更消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Model日志',
                'verbose_name_plural': 'Model日志',
                'ordering': ('-time_added',),
            },
        ),
    ]
