# Generated by Django 2.1.7 on 2020-04-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='device_type',
            field=models.CharField(choices=[('主站', '主站'), ('备站', '站备'), ('主库', '主库'), ('从库', '从库'), ('主站主库', '主站主库'), ('备站从库', '备份从库')], default='zz', help_text='资产类型: 1(主站),2(备站),3(主库),4(从库),5(主站主库),6(备份从库)', max_length=10, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='idc_location',
            field=models.CharField(choices=[('广东', '广东'), ('武汉', '武汉'), ('上海', '上海')], default='GD', help_text='服务器位置: 1(广东),2(武汉),3(上海)', max_length=10, verbose_name='服务器位置'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='online_state',
            field=models.CharField(choices=[('未上线', '未上线'), ('已上线', '已上线'), ('待迁移', '待迁移'), ('待回收', '待回收')], default='wsx', help_text='上线状态: 1(未上线),2(已上线),3(待迁移),4(待回收)', max_length=10, verbose_name='上线状态'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='testapi_state',
            field=models.CharField(choices=[('未开通', '未开通'), ('已开通', '已开通')], default='wkt', help_text='测试api开通状态: 1(未开通),2(已开通)', max_length=10, verbose_name='测试api开通状态'),
        ),
        migrations.AlterField(
            model_name='historicaldeviceinfo',
            name='device_type',
            field=models.CharField(choices=[('主站', '主站'), ('备站', '站备'), ('主库', '主库'), ('从库', '从库'), ('主站主库', '主站主库'), ('备站从库', '备份从库')], default='zz', help_text='资产类型: 1(主站),2(备站),3(主库),4(从库),5(主站主库),6(备份从库)', max_length=10, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='historicaldeviceinfo',
            name='idc_location',
            field=models.CharField(choices=[('广东', '广东'), ('武汉', '武汉'), ('上海', '上海')], default='GD', help_text='服务器位置: 1(广东),2(武汉),3(上海)', max_length=10, verbose_name='服务器位置'),
        ),
        migrations.AlterField(
            model_name='historicaldeviceinfo',
            name='online_state',
            field=models.CharField(choices=[('未上线', '未上线'), ('已上线', '已上线'), ('待迁移', '待迁移'), ('待回收', '待回收')], default='wsx', help_text='上线状态: 1(未上线),2(已上线),3(待迁移),4(待回收)', max_length=10, verbose_name='上线状态'),
        ),
        migrations.AlterField(
            model_name='historicaldeviceinfo',
            name='testapi_state',
            field=models.CharField(choices=[('未开通', '未开通'), ('已开通', '已开通')], default='wkt', help_text='测试api开通状态: 1(未开通),2(已开通)', max_length=10, verbose_name='测试api开通状态'),
        ),
    ]
