# Generated by Django 2.1.7 on 2020-04-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20200417_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='device_type',
            field=models.CharField(choices=[('主站', '主站'), ('备站', '备站'), ('主库', '主库'), ('从库', '从库'), ('主站主库', '主站主库'), ('备站从库', '备份从库')], default='主站', help_text='资产类型: 1(主站),2(备站),3(主库),4(从库),5(主站主库),6(备份从库)', max_length=100, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='historicaldeviceinfo',
            name='device_type',
            field=models.CharField(choices=[('主站', '主站'), ('备站', '备站'), ('主库', '主库'), ('从库', '从库'), ('主站主库', '主站主库'), ('备站从库', '备份从库')], default='主站', help_text='资产类型: 1(主站),2(备站),3(主库),4(从库),5(主站主库),6(备份从库)', max_length=100, verbose_name='资产类型'),
        ),
    ]
